package Quiz6;
public class Quiz5 {
	public static void main (String[] args) {
		String str = "HVS JSFGWCB ACGH KWRSZM YBCKB HCROM WG POGSR CB HVS PFCHVSFG UFWAA JSFGWCB WH WG OPCIH O UWFZ QOZZSR ZWHHZS FSR FWRWBU VCCR OTHSF HVS FSR VCCR KVWQV WG OHHOQVSR HC O QODS CF QZCOY WB GCAS JSFGWCBG CT HVS GHCFM GVS OZKOMG KSOFG HVS UWFZ KOZYG HVFCIUV HVS KCCRG HC RSZWJSF TCCR HC VSF GWQY UFOBRACHVSF O KCZT KOBHG HC SOH HVS UWFZ PIH WG OTFOWR HC RC GC WB DIPZWQ VS ODDFCOQVSG HVS UWFZ OBR GVS BOWJSZM HSZZG VWA KVSFS GVS WG UCWBU VS GIUUSGHG HVS UWFZ DWQY GCAS TZCKSFG KVWQV GVS RCSG WB HVS ASOBHWAS VS UCSG HC HVS UFOBRACHVSF'G VCIGS OBR UOWBG SBHFM PM DFSHSBRWBU HC PS HVS UWFZ VS SOHG HVS UFOBRACHVSF KVCZS OBR KOWHG TCF HVS UWFZ RWGUIWGSR OG HVS UFOBRACHVSF KVSB HVS UWFZ OFFWJSG VS SOHG VSF KVCZS HCC O VIBHSF VCKSJSF QCASG HC HVS FSGQIS OBR QIHG HVS KCZT CDSB ZWHHZS FSR FWRWBU VCCR OBR VSF UFOBRACHVSF SASFUS IBVOFASR HVSM TWZZ HVS KCZTG PCRM KWHV VSOJM GHCBSG KVWQV YWZZ VWA CHVSF JSFGWCBG CT HVS GHCFM VOJS VOR HVS UFOBRACHVSF GVIH WB HVS QZCGSH WBGHSOR CT SOHSB OBR GCAS VOJS ZWHHZS FSR FWRWBU VCCR GOJSR PM HVS VIBHSF OG HVS KCZT ORJOBQSG CB VSF FOHVSF HVOB OTHSF GVS WG SOHSB HVS HOZS AOYSG HVS QZSOFSGH QCBHFOGH PSHKSSB HVS GOTS KCFZR CT HVS JWZZOUS OBR HVS ROBUSFG CT HVS TCFSGH, QCBJSBHWCBOZ OBHWHVSGSG HVOH OFS SGGSBHWOZZM ASRWSJOZ HVCIUV BC JSFGWCBG OFS OG CZR OG HVOH WH OZGC GSSAG HC PS O GHFCBU ACFOZWHM HOZS HSOQVWBU QVWZRFSB BCH HC KOBRSF CTT HVS DOHV";
		int[] chars = new int[27];
		for (int i = 0; i < chars.length; ++i) {
			chars[i] = 0;
		}
		for (int i = 0; i < str.length(); ++i) {
			if (!(str.charAt(i) == ' ')) 
				++chars[Math.abs((int)str.charAt(i)-65)];
		}
		
		int max = 0;
		char letter = 'x';
		for (int i = 0; i < chars.length; ++i) {
			if (chars[i] > max) {
				max = chars[i];
				letter = (char)(i+65);
			}
		}
		
		int offset = (int)letter - 69;
		
		int letterIndex = 0;
		System.out.println("Most used char: " + letter + " | offset: " + offset);
		for (int i = 0; i < str.length(); ++i) {
			letterIndex = (int)str.charAt(i) -65 -offset;
			if (letterIndex < 0) {
				letterIndex += 26;
			}
			System.out.print((char)(letterIndex+65));
		}
	}
}